[profile.default]
solc = '0.8.20'
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
optimizer = true
optimizer_runs = 10000
remappings = [
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=node_modules/forge-std/src/",
  "cannon-std/=node_modules/cannon-std/src/",
  "@interfaces/=src/interfaces/",
  "@storage/=src/storage/",
  "@modules/=src/modules/",
  "@errors/=src/errors/",
  "@utils/=src/utils/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
line_length = 90
tab_width = 4
bracket_spacing = false
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'attributes_first'