# [contract.mockstETH]
# artifact = "MockTestToken"
# args = ["stETH", "stETH", "18", "<%= parseUnits('10', 18) %>"]

[clone.pstETH]
source = "pike-upgradeable-proxy:0.1.0@main"
options.implementation = "<%= contracts.PTokenRouter.address %>"
options.owner = "<%= settings.protocol_owner %>"
options.abi = "<%= JSON.stringify(contracts.PTokenRouter.abi) %>"

[invoke.chainlink_set_stETH]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.stETH_address %>", "<%= settings.stETH_chainlinkFeed %>", "<%= settings.stETH_maxStale %>"]
depends = [ "invoke.initialize_chainlink"]

[invoke.pyth_set_stETH]
target = ["pythOracleProvider.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.stETH_address %>", "<%= settings.stETH_pythID %>", "0", "<%= settings.stETH_maxStale %>"]
depends = [ "invoke.initialize_pyth"]

[invoke.mockProvider_set_stETH]
target = ["MockProvider"]
func = "setPrice"
args = ["<%= settings.stETH_address %>", "<%= settings.stETH_mockPrice %>", "18"]
depends = [ "contract.MockProvider" ]

[invoke.oe_set_stETH]
target = ["oracleEngine.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.stETH_address %>", "<%= contracts.MockProvider.address %>", "<%= AddressZero %>", "0", "0"]
depends = [ "contract.MockProvider" ]

[invoke.initialize_pstETH]
target = [ "pstETH.Proxy" ]
fromCall.func = "owner"
func = "initialize(address,address,uint256,uint256,uint256,uint256,string,string,uint8)"
args = ["<%= settings.stETH_address %>", "<%= core.Proxy.address %>", "<%= settings.stETH_initial_exchange_rate %>", "<%= settings.stETH_reserve_factor %>", "<%= settings.stETH_protocol_seize_factor %>", "<%= settings.stETH_max_borrow_rate %>", "pike-steth", "pstETH", "<%= settings.stETH_decimals %>"]
depends = [ "clone.pstETH",  "clone.core"]


[invoke.config_pstETH_IRM]
target = [ "pstETH.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "configureInterestRateModel"
args = ["<%= settings.stETH_baseRate %>", "<%= settings.stETH_multiplier %>", "<%= settings.stETH_firstJumpMultiplier %>", "<%= settings.stETH_secondJumpMultiplier %>", "<%= settings.stETH_firstKink %>", "<%= settings.stETH_secondKink %>"]
depends = [ "clone.pstETH", "invoke.set_core_configurator" ]


[invoke.support_pstETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "supportMarket"
args = ["<%= pstETH.Proxy.address %>"]
depends = ["invoke.set_core_configurator"]

[invoke.configure_pstETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "configureMarket"
args = ["<%= pstETH.Proxy.address %>", ["<%= settings.stETH_maxLTV %>", "<%= settings.stETH_LLTV %>", "<%= settings.stETH_LiqIncentive %>"]]
depends = ["invoke.set_core_configurator", "invoke.support_pstETH"]

[invoke.set_close_factor_pstETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setCloseFactor"
args = ["<%= pstETH.Proxy.address %>", "<%= settings.core_closeFactor %>"]
depends = ["invoke.set_core_configurator", "invoke.support_pstETH"]

[invoke.set_borrow_cap_pSTETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setMarketBorrowCaps"
args = [["<%= pstETH.Proxy.address %>"], ["<%= settings.stETH_borrowCap %>"]]
depends = ["invoke.set_core_borrow_guard"]

[invoke.set_supply_cap_pSTETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setMarketSupplyCaps"
args = [["<%= pstETH.Proxy.address %>"], ["<%= settings.stETH_supplyCap %>"]]
depends = ["invoke.set_core_supply_guard"]


