# [contract.mockUSDC]
# artifact = "MockTestToken"
# args = ["USDC", "USDC", "6", "<%= parseUnits('20000', 6) %>"]

[clone.pUSDC]
source = "pike-upgradeable-proxy:0.1.0@main"
options.implementation = "<%= contracts.PTokenRouter.address %>"
options.owner = "<%= settings.protocol_owner %>"
options.abi = "<%= JSON.stringify(contracts.PTokenRouter.abi) %>"

[invoke.chainlink_set_usdc]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.usdc_address %>", "<%= settings.usdc_chainlinkFeed %>", "<%= settings.usdc_maxStale %>"]
depends = [ "invoke.initialize_chainlink"]

[invoke.pyth_set_usdc]
target = ["pythOracleProvider.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.usdc_address %>", "<%= settings.usdc_pythID %>", "0", "<%= settings.usdc_maxStale %>"]
depends = [ "invoke.initialize_pyth"]

[invoke.oe_set_usdc]
target = ["oracleEngine.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.usdc_address %>", "<%= pythOracleProvider.Proxy.address %>", "<%= chainlinkOracleProvider.Proxy.address %>", "0", "0"]
depends = [ "invoke.pyth_set_usdc", "invoke.chainlink_set_usdc"]

[invoke.initialize_pUSDC]
target = [ "pUSDC.Proxy" ]
fromCall.func = "owner"
func = "initialize(address,address,uint256,uint256,uint256,uint256,string,string,uint8)"
args = ["<%= settings.usdc_address %>", "<%= core.Proxy.address %>", "<%= settings.usdc_initial_exchange_rate %>", "<%= settings.usdc_reserve_factor %>", "<%= settings.usdc_protocol_seize_factor %>", "<%= settings.usdc_max_borrow_rate %>", "pike-usdc", "pUSDC", "<%= settings.usdc_decimals %>"]
depends = [ "clone.pUSDC",  "clone.core"]

[invoke.config_pUSDC_IRM]
target = [ "pUSDC.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "configureInterestRateModel"
args = ["<%= settings.usdc_baseRate %>", "<%= settings.usdc_multiplier %>", "<%= settings.usdc_firstJumpMultiplier %>", "<%= settings.usdc_secondJumpMultiplier %>", "<%= settings.usdc_firstKink %>", "<%= settings.usdc_secondKink %>"]
depends = [ "clone.pUSDC", "invoke.set_core_configurator" ]

[invoke.support_pUSDC]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "supportMarket"
args = ["<%= pUSDC.Proxy.address %>"]
depends = ["invoke.set_core_configurator"]

[invoke.configure_pUSDC]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "configureMarket"
args = ["<%= pUSDC.Proxy.address %>", ["<%= settings.usdc_maxLTV %>", "<%= settings.usdc_LLTV %>", "<%= settings.usdc_LiqIncentive %>"]]
depends = ["invoke.set_core_configurator", "invoke.support_pUSDC"]

[invoke.set_close_factor_pUSDC]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setCloseFactor"
args = ["<%= pUSDC.Proxy.address %>", "<%= settings.core_closeFactor %>"]
depends = ["invoke.set_core_configurator", "invoke.support_pUSDC"]

[invoke.set_borrow_cap_pUSDC]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setMarketBorrowCaps"
args = [["<%= pUSDC.Proxy.address %>"], ["<%= settings.usdc_borrowCap %>"]]
depends = ["invoke.set_core_borrow_guard"]

[invoke.set_supply_cap_pUSDC]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setMarketSupplyCaps"
args = [["<%= pUSDC.Proxy.address %>"], ["<%= settings.usdc_supplyCap %>"]]
depends = ["invoke.set_core_supply_guard"]

