# [contract.mockWETH]
# artifact = "MockTestToken"
# args = ["Wrapped Ether", "WETH", "18", "<%= parseUnits('10', 18) %>"]

[clone.pWETH]
source = "pike-upgradeable-proxy:0.1.0@main"
options.implementation = "<%= contracts.PTokenRouter.address %>"
options.owner = "<%= settings.protocol_owner %>"
options.abi = "<%= JSON.stringify(contracts.PTokenRouter.abi) %>"

[invoke.chainlink_set_weth]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.weth_address %>", "<%= settings.weth_chainlinkFeed %>", "<%= settings.weth_maxStale %>"]
depends = [ "invoke.initialize_chainlink"]

[invoke.pyth_set_weth]
target = ["pythOracleProvider.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.weth_address %>", "<%= settings.weth_pythID %>", "0", "<%= settings.weth_maxStale %>"]
depends = [ "invoke.initialize_pyth"]

[invoke.mockProvider_set_weth]
target = ["MockProvider"]
func = "setPrice"
args = ["<%= settings.weth_address %>", "<%= settings.weth_mockPrice %>", "18"]
depends = [ "contract.MockProvider" ]

[invoke.oe_set_weth]
target = ["oracleEngine.Proxy"]
func = "setAssetConfig"
fromCall.func = "owner"
args = ["<%= settings.weth_address %>",  "<%= chainlinkOracleProvider.Proxy.address %>",  "<%= pythOracleProvider.Proxy.address %>", "0", "0"]
depends = [ "contract.MockProvider" ]

[invoke.initialize_pWETH]
target = [ "pWETH.Proxy" ]
fromCall.func = "owner"
func = "initialize(address,address,uint256,uint256,uint256,uint256,string,string,uint8)"
args = ["<%= settings.weth_address %>", "<%= core.Proxy.address %>", "<%= settings.weth_initial_exchange_rate %>", "<%= settings.weth_reserve_factor %>", "<%= settings.weth_protocol_seize_factor %>", "<%= settings.weth_max_borrow_rate %>", "pike-weth", "pWETH", "<%= settings.weth_decimals %>"]
depends = [ "clone.pWETH",  "clone.core"]


[invoke.config_pWETH_IRM]
target = [ "pWETH.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "configureInterestRateModel"
args = ["<%= settings.weth_baseRate %>", "<%= settings.weth_multiplier %>", "<%= settings.weth_firstJumpMultiplier %>", "<%= settings.weth_secondJumpMultiplier %>", "<%= settings.weth_firstKink %>", "<%= settings.weth_secondKink %>"]
depends = [ "clone.pWETH", "invoke.set_core_configurator" ]

[invoke.support_pWETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "supportMarket"
args = ["<%= pWETH.Proxy.address %>"]
depends = ["invoke.set_core_configurator"]

[invoke.configure_pWETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "configureMarket"
args = ["<%= pWETH.Proxy.address %>", ["<%= settings.weth_maxLTV %>", "<%= settings.weth_LLTV %>", "<%= settings.weth_LiqIncentive %>"]]
depends = ["invoke.set_core_configurator", "invoke.support_pWETH"]

[invoke.set_close_factor_pWETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setCloseFactor"
args = ["<%= pWETH.Proxy.address %>", "<%= settings.core_closeFactor %>"]
depends = ["invoke.set_core_configurator", "invoke.support_pWETH"]

[invoke.set_borrow_cap_pWETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setMarketBorrowCaps"
args = [["<%= pWETH.Proxy.address %>"], ["<%= settings.weth_borrowCap %>"]]
depends = ["invoke.set_core_borrow_guard"]

[invoke.set_supply_cap_pWETH]
target = [ "core.Proxy" ]
from = "<%= settings.core_configurator %>"
func = "setMarketSupplyCaps"
args = [["<%= pWETH.Proxy.address %>"], ["<%= settings.weth_supplyCap %>"]]
depends = ["invoke.set_core_supply_guard"]


