include = [
    # global implementation deployment 
    "./global.toml",
]

[contract.Factory]
artifact = "Factory"
from = "<%= settings.deployer %>"

[contract.reBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.RiskEngineRouter.address %>",
  "<%= settings.core_owner %>"
]
from = "<%= settings.deployer %>"

[contract.pTokenBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.PTokenRouter.address %>",
  "<%= settings.core_owner %>"
]
from = "<%= settings.deployer %>"

[contract.timelockBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.Timelock.address %>",
  "<%= settings.core_owner %>"
]
from = "<%= settings.deployer %>"

[contract.oracleEngineBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.OracleEngine.address %>",
  "<%= settings.core_owner %>"
]
from = "<%= settings.deployer %>"

[contract.factoryProxy]
artifact = "ERC1967Proxy"
args = [
  "<%= contracts.Factory.address %>",
  "<%= encodeFunctionData({abi: contracts.Factory.abi, functionName: 'initialize', args: [settings.core_owner, contracts.reBeacon.address, contracts.oracleEngineBeacon.address, contracts.pTokenBeacon.address, contracts.timelockBeacon.address]}) %>"
]
from = "<%= settings.deployer %>"
depends = ['contract.Factory','contract.oracleEngineBeacon', 'contract.reBeacon', 'contract.pTokenBeacon', 'contract.timelockBeacon']