[contract.Factory]
artifact = "src/factory/Factory.sol:Factory"

[contract.Timelock]
artifact = "src/factory/Timelock.sol:Timelock"

[contract.InitialModuleBeacon]
artifact = "src/pike-market/modules/InitialModuleBeacon.sol:InitialModuleBeacon"

[contract.DoubleJumpRateModel]
artifact = "DoubleJumpRateModel"

[contract.RBACModule]
artifact = "RBACModule"

[contract.PTokenModule]
artifact = "PTokenModule"

[contract.RiskEngineModule]
artifact = "RiskEngineModule"

[contract.OracleEngine]
artifact = "OracleEngine"

#PToken
[router.PTokenRouter]
contracts = [
    "InitialModuleBeacon",
    "DoubleJumpRateModel",
    "RBACModule",
    "PTokenModule",
]

[router.RiskEngineRouter]
contracts = [
    "InitialModuleBeacon",
    "RBACModule",
    "RiskEngineModule",
]

[contract.reBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.RiskEngineRouter.address %>",
  "<%= settings.core_owner %>"
]

[contract.pTokenBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.PTokenRouter.address %>",
  "<%= settings.core_owner %>"
]

[contract.timelockBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.Timelock.address %>",
  "<%= settings.core_owner %>"
]

[contract.oracleEngineBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.OracleEngine.address %>",
  "<%= settings.core_owner %>"
]

[clone.factory]
source = "pike-upgradeable-proxy:0.1.0@oz"
options.implementation = "<%= contracts.Factory.address %>"
options.initialCallData = "<%= encodeFunctionData({abi: contracts.Factory.abi, functionName: 'initialize', args: [settings.core_owner, contracts.reBeacon.address, contracts.oracleEngineBeacon.address, contracts.pTokenBeacon.address, contracts.timelockBeacon.address]}) %>"
options.owner = "<%= settings.core_owner %>"
options.abi = "<%= JSON.stringify(contracts.Factory.abi) %>"
options.salt = "Factory"


