name = "pike-market-local"
version = "0.1.0"
description = "Build factory beacon routers"

include = [
    # global implementation deployment 
    "./global.toml",
]

[var.owner]
owner = "0x8da29648bd3bbef6f0cc1C0b3a9a286ED14E2963"

[contract.reBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.RiskEngineRouter.address %>",
  "<%= settings.owner %>"
]

[contract.pTokenBeacon]
artifact = "UpgradeableBeacon"
args = [
  "<%= contracts.PTokenRouter.address %>",
  "<%= settings.owner %>"
]