name = "pike-local-market"
version = "0.1.0"
description = "Local markets for Pike mainnet deployment"
include = ["testnet.toml"]
# override with mainnet values and mock oracle for test

[setting.usdc]
defaultValue = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"

[setting.weth]
defaultValue = "0x4200000000000000000000000000000000000006"

[contract.PythOracleProvider]
artifact = "PythOracleProvider"
args = ["0x8250f4aF4B972684F7b336503E2D6dFeDeB1487a"]

[invoke.chainlink_set_weth]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.weth %>", "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70", "<%= MaxUint256 %>"]
depends = [ "invoke.initialize_chainlink"]

[invoke.chainlink_set_usdc]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.usdc %>", "0x7e860098F58bBFC8648a4311b374B1D669a2bc6B", "<%= MaxUint256 %>"]
depends = [ "invoke.initialize_chainlink"]