name = "pike-market"
version = "0.1.0"
description = "Local markets for Pike testnet deployment"

# `salt` here only affects proxy contract
[setting.salt]
description = "Change this to a unique string when deploying multiple instances of the ptoken. Note that only the proxy contract will be unique."
defaultValue = "main"

[setting.owner]
description = "Admin user for the system"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.usdc]
defaultValue = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"

[setting.weth]
defaultValue = "0x4200000000000000000000000000000000000006"

[setting.initial_exchange_rate]
defaultValue = "1000000000000000000" # 1e18

[setting.reserve_factor]
defaultValue = "50000000000000000" # 5e16 = 5%

[setting.protocol_seize_factor]
defaultValue = "10000000000000000" # 1e16 = 1%

[setting.max_borrow_rate]
defaultValue = "5000000000000" # 5e12

[setting.decimals]
defaultValue = "18"

[contract.InitialModuleBundle]
artifact = "InitialModuleBundle"
salt = "<%= settings.salt %>"
create2 = true

[contract.InterestRateModule]
artifact = "InterestRateModule"

[contract.PTokenModule]
artifact = "PTokenModule"

[contract.RiskEngineModule]
artifact = "RiskEngineModule"

[contract.OracleEngine]
artifact = "OracleEngine"

[contract.ChainlinkOracleProvider]
artifact = "ChainlinkOracleProvider"
args = ["<%= AddressZero %>"]

[contract.PythOracleProvider]
artifact = "PythOracleProvider"
args = ["0xA2aa501b19aff244D90cc15a4Cf739D2725B5729"]

#PToken
[router.PTokenRouter]
contracts = [
    "InitialModuleBundle",
    "InterestRateModule",
    "PTokenModule",
]

#Core
[router.CoreRouter]
contracts = [
    "InitialModuleBundle",
    "RiskEngineModule",
]

[clone.oracleEngine]
source = "universal-upgradeable-proxy:0.1.0@erc1967-upgrade"
options.implementation = "<%= contracts.OracleEngine.address %>"
options.owner = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(contracts.OracleEngine.abi) %>"
options.salt = "oracleEngine"

[clone.chainlinkOracleProvider]
source = "universal-upgradeable-proxy:0.1.0@erc1967-upgrade"
options.implementation = "<%= contracts.ChainlinkOracleProvider.address %>"
options.owner = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(contracts.ChainlinkOracleProvider.abi) %>"
options.salt = "chainlinkOracleProvider"

[clone.pythOracleProvider]
source = "universal-upgradeable-proxy:0.1.0@erc1967-upgrade"
options.implementation = "<%= contracts.PythOracleProvider.address %>"
options.owner = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(contracts.PythOracleProvider.abi) %>"
options.salt = "pythOracleProvider"

[clone.pUSDC]
source = "universal-upgradeable-proxy:0.1.0@module-upgrade"
options.implementation = "<%= contracts.PTokenRouter.address %>"
options.owner = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(contracts.PTokenRouter.abi) %>"
options.salt = "pUSDC"

[clone.pWETH]
source = "universal-upgradeable-proxy:0.1.0@module-upgrade"
options.implementation = "<%= contracts.PTokenRouter.address %>"
options.owner = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(contracts.PTokenRouter.abi) %>"
options.salt = "pWETH"

[clone.core]
source = "universal-upgradeable-proxy:0.1.0@module-upgrade"
options.implementation = "<%= contracts.CoreRouter.address %>"
options.owner = "<%= settings.owner %>"
options.abi = "<%= JSON.stringify(contracts.CoreRouter.abi) %>"

[invoke.initialize_oe]
target = ["oracleEngine.Proxy"]
func = "initialize"
args = ["<%= settings.owner %>"]
depends = [ "clone.oracleEngine"]

[invoke.initialize_chainlink]
target = ["chainlinkOracleProvider.Proxy"]
func = "initialize"
args = ["<%= settings.owner %>"]
depends = [ "clone.chainlinkOracleProvider"]

[invoke.initialize_pyth]
target = ["pythOracleProvider.Proxy"]
func = "initialize"
args = ["<%= settings.owner %>"]
depends = [ "clone.pythOracleProvider"]

[invoke.chainlink_set_weth]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.weth %>", "0x4aDC67696bA383F43DD60A9e78F2C97Fbbfc7cb1", "<%= MaxUint256 %>"]
depends = [ "invoke.initialize_chainlink"]

[invoke.chainlink_set_usdc]
target = ["chainlinkOracleProvider.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.usdc %>", "0xd30e2101a97dcbAeBCBC04F14C3f624E67A35165", "<%= MaxUint256 %>"]
depends = [ "invoke.initialize_chainlink"]

[invoke.pyth_set_weth]
target = ["pythOracleProvider.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.weth %>", "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace", "<%= MaxUint256 %>"]
depends = [ "invoke.initialize_pyth"]

[invoke.pyth_set_usdc]
target = ["pythOracleProvider.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.usdc %>", "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a", "<%= MaxUint256 %>"]
depends = [ "invoke.initialize_pyth"]

[invoke.oe_set_weth]
target = ["oracleEngine.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.weth %>", "<%= chainlinkOracleProvider.Proxy.address %>", "<%= pythOracleProvider.Proxy.address %>", "0", "0"]
depends = [ "invoke.pyth_set_weth", "invoke.chainlink_set_weth"]

[invoke.oe_set_usdc]
target = ["oracleEngine.Proxy"]
func = "setAssetConfig"
from = "<%= settings.owner %>"
args = ["<%= settings.usdc %>", "<%= chainlinkOracleProvider.Proxy.address %>", "<%= pythOracleProvider.Proxy.address %>", "0", "0"]
depends = [ "invoke.pyth_set_usdc", "invoke.chainlink_set_usdc"]

[invoke.initialize_pUSDC]
target = [ "pUSDC.Proxy" ]
abi = "<%= JSON.stringify(contracts.PTokenModule.abi) %>"
from = "<%= settings.owner %>"
func = "initialize"
args = ["<%= settings.usdc %>", "<%= core.Proxy.address %>", "<%= settings.initial_exchange_rate %>", "<%= settings.reserve_factor %>", "<%= settings.protocol_seize_factor %>", "<%= settings.max_borrow_rate %>", "pike-usdc", "pUSDC", "<%= settings.decimals %>"]
depends = [ "clone.pUSDC",  "clone.core"]

[invoke.initialize_pWETH]
target = [ "pWETH.Proxy" ]
abi = "<%= JSON.stringify(contracts.PTokenModule.abi) %>"
from = "<%= settings.owner %>"
func = "initialize"
args = ["<%= settings.weth %>", "<%= core.Proxy.address %>", "<%= settings.initial_exchange_rate %>", "<%= settings.reserve_factor %>", "<%= settings.protocol_seize_factor %>", "<%= settings.max_borrow_rate %>", "pike-weth", "pWETH", "<%= settings.decimals %>"]
depends = [ "clone.pWETH", "clone.core" ]

[invoke.initialize_pUSDC_IRM]
target = [ "pUSDC.Proxy" ]
abi = "<%= JSON.stringify(contracts.InterestRateModule.abi) %>"
from = "<%= settings.owner %>"
func = "initialize"
args = ["<%= parseUnits('1.5', 16) %>", "<%= parseUnits('8.33', 16) %>", "<%= parseUnits('4.3', 18) %>", "<%= parseUnits('80', 16) %>"]
depends = [ "clone.pUSDC" ]

[invoke.initialize_pWETH_IRM]
target = [ "pWETH.Proxy" ]
abi = "<%= JSON.stringify(contracts.InterestRateModule.abi) %>"
from = "<%= settings.owner %>"
func = "initialize"
args = ["<%= parseUnits('1.5', 16) %>", "<%= parseUnits('8.33', 16) %>", "<%= parseUnits('4.3', 18) %>", "<%= parseUnits('80', 16) %>"]
depends = [ "clone.pWETH" ]

[invoke.set_oracle]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setOracle"
args = ["<%= oracleEngine.Proxy.address %>"]

[invoke.set_close_factor]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setCloseFactor"
args = ["<%= parseUnits('50', 16) %>"]

[invoke.support_pWETH]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "supportMarket"
args = ["<%= pWETH.Proxy.address %>"]

[invoke.support_pUSDC]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "supportMarket"
args = ["<%= pUSDC.Proxy.address %>"]

[invoke.set_pWETH_collateral_factor]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setCollateralFactor"
args = ["<%= pWETH.Proxy.address %>", "<%= parseUnits('72.5', 16) %>", "<%= parseUnits('82.5', 16) %>"]
depends = [ "invoke.support_pWETH" ]

[invoke.set_pUSDC_collateral_factor]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setCollateralFactor"
args = ["<%= pUSDC.Proxy.address %>", "<%= parseUnits('74.5', 16) %>", "<%= parseUnits('84.5', 16) %>"]
depends = [ "invoke.support_pUSDC" ]

[invoke.set_liquidation_incentive]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setLiquidationIncentive"
args = ["<%= parseUnits('1.08', 18) %>"]

[invoke.set_borrow_cap_guardian]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setBorrowCapGuardian"
args = ["<%= settings.owner %>"]

[invoke.set_supply_cap_guardian]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setSupplyCapGuardian"
args = ["<%= settings.owner %>"]

[invoke.set_pause_cap_guardian]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setPauseGuardian"
args = ["<%= settings.owner %>"]

[invoke.set_borrow_cap]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setMarketBorrowCaps"
args = [["<%= pWETH.Proxy.address %>", "<%= pUSDC.Proxy.address %>"], ["<%= MaxUint256 %>", "<%= MaxUint256 %>"]]
depends = [ "invoke.set_borrow_cap_guardian" ]

[invoke.set_supply_cap]
target = [ "core.Proxy" ]
abi = "<%= JSON.stringify(contracts.RiskEngineModule.abi) %>"
from = "<%= settings.owner %>"
func = "setMarketSupplyCaps"
args = [["<%= pWETH.Proxy.address %>", "<%= pUSDC.Proxy.address %>"], ["<%= MaxUint256 %>", "<%= MaxUint256 %>"]]
depends = [ "invoke.set_supply_cap_guardian" ]


