[var.owner]
core_owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
oracleEngine_owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
chainlinkProvider_owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
pythProvider_owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
usdc_owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
weth_owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[var.usdc]
usdc_reserveManager = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
usdc_reserveWithdrawer = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
usdc_configurator = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
usdc_supplyGuard = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
usdc_borrowGuard = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
usdc_decimals = "18"
usdc_address = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
usdc_maxLTV = "<%= parseUnits('74.5', 16) %>" #74.5%
usdc_LLTV = "<%= parseUnits('84.5', 16) %>" #84.5%
usdc_initial_exchange_rate = "<%= parseUnits('1', 18) %>" # 1e18
usdc_reserve_factor = "<%= parseUnits('5', 16) %>" # 5%
usdc_protocol_seize_factor = "<%= parseUnits('1', 16) %>" # 1%
usdc_max_borrow_rate = "<%= parseUnits('5', 12) %>" # 5e12
usdc_chainlinkFeed = "0xd30e2101a97dcbAeBCBC04F14C3f624E67A35165"
usdc_pythID = "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
usdc_maxStale = "<%= MaxUint256 %>"
usdc_supplyCap = "<%= MaxUint256 %>"
usdc_borrowCap = "<%= MaxUint256 %>"
#IRM
usdc_baseRate = "0"
usdc_multiplier = "0"
usdc_firstJumpMultiplier = "<%= parseUnits('6.111111', 16) %>"
usdc_secondJumpMultiplier = "<%= parseUnits('6', 18) %>"
usdc_firstKink = "<%= parseUnits('5', 16) %>"
usdc_secondKink = "<%= parseUnits('95', 16) %>"

[var.weth]
weth_reserveManager = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
weth_reserveWithdrawer = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
weth_configurator = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
weth_supplyGuard = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
weth_borrowGuard = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
weth_decimals = "18"
weth_address = "0x4200000000000000000000000000000000000006"
weth_maxLTV = "<%= parseUnits('72.5', 16) %>" #72.5%
weth_LLTV = "<%= parseUnits('82.5', 16) %>" #82.5%
weth_initial_exchange_rate = "<%= parseUnits('1', 18) %>" # 1e18
weth_reserve_factor = "<%= parseUnits('5', 16) %>" # 5%
weth_protocol_seize_factor = "<%= parseUnits('1', 16) %>" # 1%
weth_max_borrow_rate = "<%= parseUnits('5', 12) %>" # 5e12
weth_chainlinkFeed = "0x4aDC67696bA383F43DD60A9e78F2C97Fbbfc7cb1"
weth_pythID = "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace"
weth_maxStale = "<%= MaxUint256 %>"
weth_supplyCap = "<%= MaxUint256 %>"
weth_borrowCap = "<%= MaxUint256 %>"
#IRM
weth_baseRate = "0"
weth_multiplier = "0"
weth_firstJumpMultiplier = "<%= parseUnits('6.111111', 16) %>"
weth_secondJumpMultiplier = "<%= parseUnits('6', 18) %>"
weth_firstKink = "<%= parseUnits('5', 16) %>"
weth_secondKink = "<%= parseUnits('95', 16) %>"

[var.params]
core_configurator = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
core_pauseGuard = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
core_closeFactor = "<%= parseUnits('50', 16) %>"
core_incentives = "<%= parseUnits('1.08', 18) %>"

[var.salt]
salt = "main"

[var.oracle]
chianlinkSequencerFeed = "0xBCF85224fc0756B9Fa45aA7892530B47e10b6433"
pythAddress = "0xA2aa501b19aff244D90cc15a4Cf739D2725B5729"
