[clone.pythOracleProvider]
source = "pike-upgradeable-proxy:0.1.0@oz"
options.implementation = "<%= contracts.PythOracleProvider.address %>"
options.owner = "<%= settings.pythProvider_owner %>"
options.abi = "<%= JSON.stringify(contracts.PythOracleProvider.abi) %>"
options.salt = "pythOracleProvider"

[invoke.initialize_pyth]
target = ["pythOracleProvider.Proxy"]
func = "initialize"
args = ["<%= settings.pythProvider_owner %>"]
depends = [ "clone.pythOracleProvider"]