include = [
    # global params 
    # "../global.toml",

    # core factory
    "../core.toml",

    # oracle provider
    "./oracle-provider.toml",
]

[var.owner]
core_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
deployer = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
oracleEngine_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
chainlinkProvider_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
pythProvider_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
usdc_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
weth_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"
steth_owner = "0xE80bbcAB9E20fc193Ef768B68d69F363a7f9a2a1"

[var.config]
pythFeed = "0x8250f4aF4B972684F7b336503E2D6dFeDeB1487a"
chainlinkUptimeFeed = "0xBCF85224fc0756B9Fa45aA7892530B47e10b6433"

[var.salts]
salts_initialModuleBeacon = "Pike-InitialModuleBeacon-Impl-v1.0.1@663bb92-Prod"
salts_doubleJumpRateModel = "Pike-DoubleJumpRateModel-Impl-v1.0.1@663bb92-Prod"
salts_rbacModule = "Pike-RBACModule-Impl-v1.0.1@663bb92-Prod"
salts_pTokenModule = "Pike-PTokenModule-Impl-v1.0.1@663bb92-Prod"
salts_riskEngineModule = "Pike-RiskEngineModule-Impl-v1.0.1@663bb92-Prod"
salts_oracleEngine = "Pike-OracleEngine-Impl-v1.0.1@663bb92-Prod"
salts_timelock = "Pike-Timelock-Impl-v1.0.1@663bb92-Prod"
salts_pTokenRouter = "Pike-PTokenRouter-Impl-v1.0.1@663bb92-Prod"
salts_riskEngineRouter = "Pike-RiskEngineRouter-Impl-v1.0.1@663bb92-Prod"
salts_factory = "Pike-Factory-Impl-v1.0.1@663bb92-Prod"
salts_riskEngineBeacon = "Pike-RiskEngine-Beacon-v1.0.1@663bb92-Prod"
salts_pTokenBeacon = "Pike-PToken-Beacon-v1.0.1@663bb92-Prod"
salts_timelockBeacon = "Pike-Timelock-Beacon-v1.0.1@663bb92-Prod"
salts_oracleEngineBeacon = "Pike-OracleEngine-Beacon-v1.0.1@663bb92-Prod"
salts_factoryProxy = "Pike-Factory-Proxy-v1.0.1@663bb92-Prod"
salts_pythOracleProvider = "Pike-PythOracleProvider-Impl-v1.0.1@663bb92-Prod"
salts_chainlinkOracleProvider = "Pike-ChainlinkOracleProvider-Impl-v1.0.1@663bb92-Prod"
salts_chainlinkOracleComposite = "Pike-ChainlinkOracleComposite-Impl-v1.0.1@663bb92-Prod"
salts_pythProviderProxy = "Pike-PythOracleProvider-Proxy-v1.0.1@663bb92-Prod"
salts_chainlinkOracleProviderProxy = "Pike-ChainlinkOracleProvider-Proxy-v1.0.1@663bb92-Prod"
salts_chainlinkOracleCompositeProxy = "Pike-ChainlinkOracleComposite-Proxy-v1.0.1@663bb92-Prod"
