name = "pike-local-market"
version = "0.1.0"
preset = "main"
description = "Local markets for Pike testnet deployment"

include = [
    # testnet core toml 
    "../base-sepolia/core.toml",
]

[var.usdc]
usdc_address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
usdc_chainlinkFeed = "0x7e860098F58bBFC8648a4311b374B1D669a2bc6B"

[var.weth]
weth_chainlinkFeed = "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70"

[var.oracle]
pythAddress = "0x8250f4aF4B972684F7b336503E2D6dFeDeB1487a"