[contract.PythOracleProvider]
artifact = "PythOracleProvider"
args = [
  "<%= settings.pythFeed %>",
  "<%= settings.pythProvider_owner %>"
]
from = "<%= settings.deployer %>"
create2=true
salt="<%= settings.salts_pythOracleProvider %>"
depends = ['var.config', 'var.owner', 'var.salts']


[contract.ChainlinkOracleProvider]
artifact = "ChainlinkOracleProvider"
args = [
  "<%= settings.chainlinkUptimeFeed %>",
  "<%= settings.chainlinkProvider_owner %>"
]
from = "<%= settings.deployer %>"
create2=true
salt="<%= settings.salts_chainlinkOracleProvider %>"
depends = ['var.config', 'var.owner', 'var.salts']

[contract.ChainlinkOracleComposite]
artifact = "ChainlinkOracleComposite"
args = [
  "<%= settings.chainlinkUptimeFeed %>",
  "<%= settings.chainlinkProvider_owner %>"
]
from = "<%= settings.deployer %>"
create2=true
salt="<%= settings.salts_chainlinkOracleComposite %>"
depends = ['var.config', 'var.owner', 'var.salts']

[contract.pythProviderProxy]
artifact = "ERC1967Proxy"
args = [
  "<%= contracts.PythOracleProvider.address %>",
  "<%= encodeFunctionData({abi: contracts.PythOracleProvider.abi, functionName: 'initialize'}) %>"
]
from = "<%= settings.deployer %>"
create2=true
salt="<%= settings.salts_pythProviderProxy %>"
depends = ['contract.PythOracleProvider']

[contract.chainlinkProviderProxy]
artifact = "ERC1967Proxy"
args = [
  "<%= contracts.ChainlinkOracleProvider.address %>",
  "<%= encodeFunctionData({abi: contracts.ChainlinkOracleProvider.abi, functionName: 'initialize'}) %>"
]
from = "<%= settings.deployer %>"
create2=true
salt="<%= settings.salts_chainlinkOracleProviderPoxy %>"
depends = ['contract.ChainlinkOracleProvider']

[contract.chainlinkCompositeProxy]
artifact = "ERC1967Proxy"
args = [
  "<%= contracts.ChainlinkOracleComposite.address %>",
  "<%= encodeFunctionData({abi: contracts.ChainlinkOracleComposite.abi, functionName: 'initialize'}) %>"
]
from = "<%= settings.deployer %>"
create2=true
salt="<%= settings.salts_chainlinkOracleCompositeProxy %>"
depends = ['contract.ChainlinkOracleComposite']