name: CI

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'early-stage') }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/setup

      - name: Lint sources
        run: yarn lint:check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'early-stage') }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment
        uses: ./.github/setup

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        id: fuzz_seed
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_OUTPUT

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Cannon tests
        run: |
          yarn test
        id: test
